# 2D Coordinate transformation

## Example 1: Calculation with one HTM 

In [1]:
from matplotlib import pyplot as plt
from numpy.linalg import inv
from IPython import display
import numpy as np
import math

PI = 3.1415926535

def plot3x3Mat(m):
    print("[%6.2f\t%6.2f\t%6.2f]"%(m[0,0],m[0,1],m[0,2]))
    print("[%6.2f\t%6.2f\t%6.2f]"%(m[1,0],m[1,1],m[1,2]))
    print("[%6.2f\t%6.2f\t%6.2f]"%(m[2,0],m[2,1],m[2,2]))
    
def IIDrotM(phi):
    m = np.array([[math.cos(float(phi)),math.sin(float(phi)),0],[-math.sin(float(phi)),math.cos(float(phi)),0],[0,0,1]])
    return m

def IIDtraM(v):
    m = np.array([[1,0,float(v[0])],[0,1,float(v[1])],[0,0,1]])
    return m

def IIDtraHTMvec(x,y):
    v = np.array([ [float(x)],[float(y)],[1] ])
    return v


### (I) Scenario

### (II) Derive tansformation parameters angle $\phi$ and translation $ ^{t}V$

#### Rotation angle $\phi$

In [2]:
phi = PI

#### Translation vectro $^tV$

In [3]:
x_t = 0
y_t = 0

In [4]:
V_t = IIDtraHTMvec(x_t,y_t)

### (III) Create HTM

#### Create HTM for rotation only

In [5]:
R_o_t = IIDrotM(phi)

In [6]:
#Output final matrix R_o_t
plot3x3Mat(R_o_t)

[ -1.00	  0.00	  0.00]
[ -0.00	 -1.00	  0.00]
[  0.00	  0.00	  1.00]


#### Create HTM for translation only

In [7]:
TR_o_t = IIDtraM(V_t)

In [8]:
#Output final matrix TR_o_t
plot3x3Mat(TR_o_t)

[  1.00	  0.00	  0.00]
[  0.00	  1.00	  0.00]
[  0.00	  0.00	  1.00]


#### Create complete HTM (incl. rotation and translation)

In [9]:
T_o_t = TR_o_t @ R_o_t

In [10]:
#Output final matrix
print("T_o_t = ",end="\n\n"); plot3x3Mat(T_o_t)

T_o_t = 

[ -1.00	  0.00	  0.00]
[ -0.00	 -1.00	  0.00]
[  0.00	  0.00	  1.00]


### (IV) Calculate vector $^tP$ for given $^oP$

$$ 
 ^{t}P ~~~ = ~~~  T_o^t ~ \cdot ~ ^{o}P 
$$

In [11]:
print("x_p_o = ", end="")
x_p_o = float(input());
print("y_p_o = ", end="")
y_p_o = float(input());


x_p_o = 1
y_p_o = 1


In [12]:
p_o = IIDtraHTMvec(x_p_o, y_p_o)

In [13]:
p_t = T_o_t @ p_o
print("p_t = ", end="\n");
print(p_t)

p_t = 
[[-1.]
 [-1.]
 [ 1.]]


### (V) Check for plausibility

In [14]:
print("P_o = ",end="\n"); print(p_o)

P_o = 
[[1.]
 [1.]
 [1.]]


In [15]:
print("P_t = ",end="\n"); print(p_t)

P_t = 
[[-1.]
 [-1.]
 [ 1.]]


The result seems plausible because *\<PUT YOUR ANSWER HERE...\>*