# Koordinatentransformation für die Robotik

## (3) Homogene Transformationmatrix (HTM) für die Translation und Rotation

Folgende Bibliotheken, Funktionen und Konstanten werden genutzt:

In [1]:
from matplotlib import pyplot as plt
from numpy.linalg import inv
import numpy as np
import math

PI = 3.1415926535

def plot4x4Mat(m):
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[0,0],m[0,1],m[0,2],m[0,3]))
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[1,0],m[1,1],m[1,2],m[1,3]))
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[2,0],m[2,1],m[2,2],m[2,3]))
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[3,0],m[3,1],m[3,2],m[3,3]))

### (I) Punkt im Ursprungskoordinatensystem U definieren

$$ ^{U}P = \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right) $$

In [2]:
x_U = 10.32
y_U = 19.10
z_U = 23.14
print("x_U = ",end=""); print(x_U)
print("y_U = ",end=""); print(y_U)
print("z_U = ",end=""); print(z_U)

x_U = 10.32
y_U = 19.1
z_U = 23.14


In [3]:
P_U = np.array([[x_U],[y_U],[z_U],[1]])

In [4]:
#Ausgabe der Berechnungsergebnisse
print("P_U = ",end="\n\n"); print(P_U)

P_U = 

[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]


### (II) Definition der einzelnen HTMs

#### (II.1) Eine HTM mit Rotation erstellen

$$ 
  ^{Z}_{U}R_{ZYX}(\phi_z,\phi_y,\phi_x) =  R_Z(\phi_z) \cdot R_Y(\phi_y) \cdot R_X(\phi_x) 
$$

$$ =~~
   \left( \begin{array}{rrrr}       
      r_{1,1} & r_{1,2} & r_{1,3} & 0 \\       
      r_{2,1} & r_{3,2} & r_{2,3} & 0 \\       
      r_{3,1} & r_{2,2} & r_{3,3} & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right) 
$$



In [5]:
phi_x = PI/3
phi_y = 2*PI/5
phi_z = -PI/2

In [6]:
#Ausgabe der Berechnungsergebnisse
print("phi_x = ",end=""); print(phi_x)
print("phi_y = ",end=""); print(phi_y)
print("phi_z = ",end=""); print(phi_z)

phi_x = 1.0471975511666667
phi_y = 1.2566370614
phi_z = -1.57079632675


In [7]:
T_U_Z_RotX = np.array([[1,0,0,0],[0,math.cos(phi_x),math.sin(phi_x),0],[0,-math.sin(phi_x),math.cos(phi_x),0],[0,0,0,1]])
T_U_Z_RotY = np.array([[math.cos(phi_y),0,-math.sin(phi_y),0],[0,1,0,0],[math.sin(phi_y),0,math.cos(phi_y),0],[0,0,0,1]])
T_U_Z_RotZ = np.array([[math.cos(phi_z),math.sin(phi_z),0,0],[-math.sin(phi_z),math.cos(phi_z),0,0],[0,0,1,0],[0,0,0,1]])
T_U_Z_RotZYX = T_U_Z_RotZ @ T_U_Z_RotY @ T_U_Z_RotX

In [8]:
print("T_U_Z_RotZYX = ",end="\n"); plot4x4Mat(T_U_Z_RotZYX)

T_U_Z_RotZYX = 
[  0.00	 -0.50	 -0.87	  0.00]
[  0.31	  0.82	 -0.48	  0.00]
[  0.95	 -0.27	  0.15	  0.00]
[  0.00	  0.00	  0.00	  1.00]


#### (II.2) Eine HTM mit Translation erstellen

Der Translationsvektor $^{Z}V$ ist bzgl. des Zielekoordinatensystems $Z$ gegeben. Ohne Beschränkung der Allgemeinheit wird dieser hier nicht in homogenen Koordinaten angegeben.

In [9]:
x_V = 1.3
y_V = -3.9
z_V = 2.9

In [10]:
#Ausgabe der Berechnungsergebnisse
print("x_V = ",end=""); print(x_V)
print("y_V = ",end=""); print(y_V)
print("z_V = ",end=""); print(z_V)

x_V = 1.3
y_V = -3.9
z_V = 2.9


In [11]:
V_Z = np.array([[x_V],[y_V],[z_V],[1]])

In [12]:
#Ausgabe der Berechnungsergebnisse
print("V_Z = ",end="\n"); print(V_Z)

V_Z = 
[[ 1.3]
 [-3.9]
 [ 2.9]
 [ 1. ]]


$$ ^{Z}_{U}T_{Tran}(^{Z}V)  ~=~    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & V_x \\       
      0 & 1 & 0 & V_y \\       
      0 & 0 & 1 & V_z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
$$

In [13]:
T_U_Z_Tran = np.array([[1,0,0,x_V],[0,1,0,y_V],[0,0,1,z_V],[0,0,0,1]])

In [14]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_Tran = ",end="\n"); plot4x4Mat(T_U_Z_Tran)

T_U_Z_Tran = 
[  1.00	  0.00	  0.00	  1.30]
[  0.00	  1.00	  0.00	 -3.90]
[  0.00	  0.00	  1.00	  2.90]
[  0.00	  0.00	  0.00	  1.00]


### (III) Kombination der Rotation und Translation

Die Kombination von Rotation und Translation erfolgt durch die Hintereinanderausführung beider Transformationen. Die Kombination wird durch Multiplikation der jeweiligen HTM $^{Z}_{U}T_{Tran}(^{Z}V)$ und $^{Z}_{U}R_{ZYX}(\phi_z,\phi_y,\phi_x)$ mathematisch repräsentiert. Die Frage ist jedoch, wie die jeweils Ergbnis HTM aussieht.

#### (III.1) Erst Rotation dann Translation

Wenn zuerst die Rotation und dann die Translation zu einer Koordinatentransformation kombiniert werden sollen, dann kann dies nur über ein drittes Koordinatensystem $M$ geschehen. 
Die Koordinaten des Punktes $^{U}P$ werden in das Koordinatensystem $M$ "transformiert". Vom diesem $M$ Koordinatensystem werden die Koordinaten dann in das Ziel-Koordinatensystem $Z$ transformiert.

$$
 ^{Z}_{U}T ~~~=~~~ ^{Z}_{M}T_{Tran}(^{Z}V) ~~~\cdot~~~ ^{M}_{U}R_{ZYX}(\phi_z,\phi_y,\phi_x)
$$

$$ =~~
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & V_x \\       
      0 & 1 & 0 & V_y \\       
      0 & 0 & 1 & V_z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
~\cdot~
   \left( \begin{array}{rrrr}       
      r_{1,1} & r_{1,2} & r_{1,3} & 0 \\       
      r_{2,1} & r_{3,2} & r_{2,3} & 0 \\       
      r_{3,1} & r_{2,2} & r_{3,3} & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right) 
$$

$$ =~~
   \left( \begin{array}{rrrr}       
      r_{1,1} & r_{1,2} & r_{1,3} & V_x \\       
      r_{2,1} & r_{3,2} & r_{2,3} & V_y \\       
      r_{3,1} & r_{2,2} & r_{3,3} & V_z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right) 
$$

Wichtig ist nun, zu verstehen, dass die Transformation von $M$ zu $Z$ den Translationsvektor $^{Z}V$ unverändert übernehmen kann. Denn dieser Vektor liegt wie nach Definition verlangt in den Koordinaten des Zielsystems vor.

In [15]:
T_U_Z_1 =  T_U_Z_Tran  @ T_U_Z_RotZYX

In [16]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_1 = ",end="\n"); plot4x4Mat(T_U_Z_1)

T_U_Z_1 = 
[  0.00	 -0.50	 -0.87	  1.30]
[  0.31	  0.82	 -0.48	 -3.90]
[  0.95	 -0.27	  0.15	  2.90]
[  0.00	  0.00	  0.00	  1.00]


#### (III.2) Erst Translation dann Rotation

Auch hier erfolgt die Transformation von $U$ nach $Z$ über ein zusätzliches Koordinatensystem $N$.

$$
 ^{Z}_{U}T ~~~=~~~   ^{Z}_{N}R_{ZYX}(\phi_z,\phi_y,\phi_x) ~~~\cdot~~~ ^{N}_{U}T_{Tran}(^{N}V)
$$

Damit die Definition der Transformationsmatrix für die Translation erfüllt ist, muss der Translationsvektor $V$ in den Koordinaten des Koordinatensystems $N$ gegeben sein. Im Allgemeinen gilt $^{N}V \neq ^{Z}V$.

Wie kann nun $^{N}V$ auf Basis der vorhanden Informationen berechnet werden?

Offensichtlich benötigen wir eine Rotation, welche uns $^{Z}V$ in das Koordnatensystem $N$ überführt, denn $Z$ und $N$ sind ohne Translation nur bzgl. Rotation voneinander verschieden.

$$
    ^{N}V ~~~=~~~ ^{N}_{Z}R_{ZYX}(\phi_z,\phi_y,\phi_x)~~~\cdot~~~^{Z}V
$$

 Die Rotationsmatrix $^{Z}_{U}R_{ZYX}(\phi_z,\phi_y,\phi_x)$ ist uns geben. Da nun zwischen $N$ und $Z$ keine Tanslation besteht, gilt:
 $$
 ~~~~^{Z}_{U}R_{ZYX}(\phi_z,\phi_y,\phi_x) ~~~ = ~~~ ^{Z}_{N}R_{ZYX}(\phi_z,\phi_y,\phi_x)
 $$

Weiterhin gilt:
$$
^{N}_{Z}R_{ZYX}(\phi_z,\phi_y,\phi_x) = (^{Z}_{N}R_{ZYX}(\phi_z,\phi_y,\phi_x))^{-1}
$$
Womit sich ergibt:
$$
    ^{N}V ~~~=~~~ (^{Z}_{N}R_{ZYX}(\phi_z,\phi_y,\phi_x))^{-1}~~~\cdot~~~^{Z}V
$$

Der Vektor $^{N}V$ kann also über die Inverse der Rotationsmatrix $^{Z}_{N}R_{ZYX}(\phi_z,\phi_y,\phi_x)$ und den Vektor $^{Z}V$ berechnet werden:

$$
 ^{Z}_{U}T ~~~=~~~   ^{Z}_{N}R_{ZYX}(\phi_z,\phi_y,\phi_x) ~~~\cdot~~~ ^{N}_{U}T_{Tran}\left(\left(^{Z}_{N}R_{ZYX}(\phi_z,\phi_y,\phi_x)\right)^{-1}~~~\cdot~~~^{Z}V\right)
$$

$$ =~~
   \left( \begin{array}{rrrr}       
      r_{1,1} & r_{1,2} & r_{1,3} & 0 \\       
      r_{2,1} & r_{3,2} & r_{2,3} & 0 \\       
      r_{3,1} & r_{2,2} & r_{3,3} & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right) 
~\cdot~
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & ^{N}V_x \\       
      0 & 1 & 0 & ^{N}V_y \\       
      0 & 0 & 1 & ^{N}V_z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
$$

wobei der Translationsvektor $^{N}V$ wie folgt berechnet werden muss:

$$
^{N}V ~=~
   \left( \begin{array}{rrrr}       
      r_{1,1} & r_{1,2} & r_{1,3} & 0 \\       
      r_{2,1} & r_{2,2} & r_{2,3} & 0 \\       
      r_{3,1} & r_{3,2} & r_{3,3} & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)^{-1} 
   ~\cdot~ 
   ^{Z}V
$$
$$
 ~~~=~
   \left( \begin{array}{rrrr}       
      r_{1,1} & r_{2,1} & r_{3,1} & 0 \\       
      r_{1,2} & r_{2,2} & r_{3,3} & 0 \\       
      r_{1,3} & r_{2,3} & r_{3,3} & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
   ~\cdot~ 
   ^{Z}V
$$


In [17]:
V_N =  inv(T_U_Z_RotZYX)@V_Z

In [18]:
#Ausgabe der Berechnungsergebnisse
print("V_N = ",end="\n"); print(V_N)

V_N = 
[[ 1.55289762]
 [-4.63828055]
 [ 1.17680182]
 [ 1.        ]]


In [19]:
T_U_N_Tran = T_U_Z_Tran;
T_U_N_Tran[0,3] = V_N[0]
T_U_N_Tran[1,3] = V_N[1]
T_U_N_Tran[2,3] = V_N[2]

In [20]:
#Ausgabe der Berechnungsergebnisse
print("T_U_N_Tran = ",end="\n"); plot4x4Mat(T_U_N_Tran)

T_U_N_Tran = 
[  1.00	  0.00	  0.00	  1.55]
[  0.00	  1.00	  0.00	 -4.64]
[  0.00	  0.00	  1.00	  1.18]
[  0.00	  0.00	  0.00	  1.00]


In [21]:
T_U_Z_2 =  T_U_Z_RotZYX @ T_U_N_Tran

In [22]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_2 = ",end="\n"); plot4x4Mat(T_U_Z_2)

T_U_Z_2 = 
[  0.00	 -0.50	 -0.87	  1.30]
[  0.31	  0.82	 -0.48	 -3.90]
[  0.95	 -0.27	  0.15	  2.90]
[  0.00	  0.00	  0.00	  1.00]


#### (III.3) Vergleich der beiden Varianten

##### (A) Erst Rotation dann Translation

In [23]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_1 = ",end="\n"); plot4x4Mat(T_U_Z_1)

T_U_Z_1 = 
[  0.00	 -0.50	 -0.87	  1.30]
[  0.31	  0.82	 -0.48	 -3.90]
[  0.95	 -0.27	  0.15	  2.90]
[  0.00	  0.00	  0.00	  1.00]


##### (B) Erst Translation dann Rotation

In [24]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_2 = ",end="\n"); plot4x4Mat(T_U_Z_2)

T_U_Z_2 = 
[  0.00	 -0.50	 -0.87	  1.30]
[  0.31	  0.82	 -0.48	 -3.90]
[  0.95	 -0.27	  0.15	  2.90]
[  0.00	  0.00	  0.00	  1.00]


##### (C) Numerischer Vergleich der beiden Ergebnisse

In [25]:
#Ausgabe der Berechnungsergebnisse
if np.allclose(T_U_Z_1,T_U_Z_2,):
    print("Okay. Die beiden Berechnungen liefern gleiche Ergebnisse.")
else:
    print("In den Berechnungen muss ein fehler sein. Da diese zu unterschiedlichen Ergebnissen führten.")

Okay. Die beiden Berechnungen liefern gleiche Ergebnisse.


Die Kombination von Rotation und Translation kann also durch Matrizenmultiplikation erfolgen. Einfacher ist es jedoch erst die Rotation und dann die Translation, also Variante (A) zu nutzen. Bei dieser Variante kann die finale HTM $^{Z}_{U}T$ durch einfaches Zusammenfügen des Rotations und Translationsanteil erzeugt werden.

$$
 ^{Z}_{U}T ~~~=~~~ ^{Z}_{M}T_{Tran}(^{Z}V) ~~~\cdot~~~ ^{M}_{U}R_{ZYX}(\phi_z,\phi_y,\phi_x)
$$

$$ =~~
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & V_x \\       
      0 & 1 & 0 & V_y \\       
      0 & 0 & 1 & V_z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
~\cdot~
   \left( \begin{array}{rrrr}       
      r_{1,1} & r_{1,2} & r_{1,3} & 0 \\       
      r_{2,1} & r_{3,2} & r_{2,3} & 0 \\       
      r_{3,1} & r_{2,2} & r_{3,3} & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right) 
$$

$$ =~~
   \left( \begin{array}{rrrr}       
      r_{1,1} & r_{1,2} & r_{1,3} & V_x \\       
      r_{2,1} & r_{3,2} & r_{2,3} & V_y \\       
      r_{3,1} & r_{2,2} & r_{3,3} & V_z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right) 
$$

### (IV) Übung