# Koordinatentransformation für die Robotik

## (2) Homogene Transformationmatrix (HTM) für die Translation

Folgende Bibliotheken, Funktionen und Konstanten werden genutzt:

In [1]:
from matplotlib import pyplot as plt
from random import *
import numpy as np
import math

PI = 3.1415926535

def plot4x4Mat(m):
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[0,0],m[0,1],m[0,2],m[0,3]))
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[1,0],m[1,1],m[1,2],m[1,3]))
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[2,0],m[2,1],m[2,2],m[2,3]))
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[3,0],m[3,1],m[3,2],m[3,3]))

### (I) Punkt im Ursprungskoordinatensystem U definieren

Die Koordinaten $x$, $y$ und $z$ des Punkts $^{U}P$, also die Koordinaten von $P$ bzgl. Koordinatensystem $U$ sind in als homogene Koordinaten gegeben. Daher besitzt $^{U}P$ eine vierte Komponente, welche immer den Wert $1$ hat.

$$ ^{U}P = \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right) $$

In [2]:
x_U = 10.32
y_U = 19.10
z_U = 23.14

In [3]:
#Ausgabe der Berechnungsergebnisse
print("x_U = ",end=""); print(x_U)
print("y_U = ",end=""); print(y_U)
print("z_U = ",end=""); print(z_U)

x_U = 10.32
y_U = 19.1
z_U = 23.14


In [4]:
P_U = np.array([[x_U],[y_U],[z_U],[1]])

In [5]:
#Ausgabe der Berechnungsergebnisse
print("P_U = ",end="\n\n"); print(P_U)

P_U = 

[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]


### (II) Definition der HTM

#### (II.1) HTM: Matrixgrundstruktur (ohne Translation u. Rotation)

$$ ^{Z}_{U}T  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & 0 \\       
      0 & 1 & 0 & 0 \\       
      0 & 0 & 1 & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
$$

In [6]:
T_U_Z = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print("T_U_Z = ",end="\n\n"); plot4x4Mat(T_U_Z)

T_U_Z = 

[  1.00	  0.00	  0.00	  0.00]
[  0.00	  1.00	  0.00	  0.00]
[  0.00	  0.00	  1.00	  0.00]
[  0.00	  0.00	  0.00	  1.00]


### (II.2) HTM: Definition des Rotationsanteils

#### Rotationsmatrizen (für die Koordinatentransformation)

Rotationswinkel $\phi$ mit $\phi \in [0,2\pi)$.

Rotationsmatrizen für die Koordinatenachsen $X$, $Y$ und $Z$ als homogene Matrizen:
$$ 
   ^{Z}_{U}R_X(\phi)  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & 0 \\       
      0 & cos(\phi) & sin(\phi) & 0 \\       
      0 & -sin(\phi) & cos(\phi)& 0 \\
      0 & 0 & 0 & 1\\
   \end{array}\right)
$$

$$
   ^{Z}_{U}R_Y(\phi)  =    
   \left( \begin{array}{rrrr}       
       cos(\phi) & 0 & -sin(\phi) & 0 \\       
      0 & 1 & 0 & 0 \\       
      sin(\phi) & 0 &  cos(\phi) & 0 \\  
      0 & 0 & 0 & 1\\
   \end{array}\right)
$$   

$$
   ^{Z}_{U}R_Z(\phi)  =    
   \left( \begin{array}{rrrr}       
      cos(\phi) &  sin(\phi) & 0 & 0\\       
      -sin(\phi) & cos(\phi) & 0 & 0\\       
      0 & 0 & 1 & 0 \\
      0 & 0 & 0 & 1\\
   \end{array}\right)
$$

Der Rotationswinkel $\phi$ hat den Drehsinn vom Ursprung zum Zielkoordinatensystem und ist im folgenden in der Einheit Radiant (rad) angegeben.

In [7]:
phi = PI/4;
print("phi = ", end=""); print(phi)

phi = 0.785398163375


#### HTM mit Rotation

Wir betrachten wieder die einzelnen Rotationen, um die Achsen X, Y, Z.

##### Rotation um die X-Achse:

$$ 
   ^{Z}_{U}R_X(\phi)  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & 0 \\       
      0 & cos(\phi) & sin(\phi) & 0\\       
      0 & -sin(\phi) & cos(\phi) & 0 \\           
      0 & 0 & 0 & 1\\
   \end{array}\right)
$$

In [8]:
T_U_Z_RotX = np.array([[1,0,0,0],[0,math.cos(phi),math.sin(phi),0],[0,-math.sin(phi),math.cos(phi),0],[0,0,0,1]])

In [9]:
print("phi = ",end=""); print(phi,end="\n\n");
print("T_U_Z_RotX(phi) = ",end="\n\n"); plot4x4Mat(T_U_Z_RotX)

phi = 0.785398163375

T_U_Z_RotX(phi) = 

[  1.00	  0.00	  0.00	  0.00]
[  0.00	  0.71	  0.71	  0.00]
[  0.00	 -0.71	  0.71	  0.00]
[  0.00	  0.00	  0.00	  1.00]


##### Rotation um die y-Achse:

$$
   ^{Z}_{U}R_Y(\phi)  =    
   \left( \begin{array}{rrrr}       
       cos(\phi) & 0 & -sin(\phi) & 0 \\       
      0 & 1 & 0 & 0 \\       
      sin(\phi) & 0 &  cos(\phi) & 0 \\
       0 & 0 & 0 & 1\\
   \end{array}\right)
$$ 

In [10]:
T_U_Z_RotY = np.array([[math.cos(phi),0,-math.sin(phi),0],[0,1,0,0],[math.sin(phi),0,math.cos(phi),0],[0,0,0,1]])

In [11]:
print("phi = ",end=""); print(phi,end="\n\n");
print("T_U_Z_RotY(phi) = ",end="\n\n"); plot4x4Mat(T_U_Z_RotY)

phi = 0.785398163375

T_U_Z_RotY(phi) = 

[  0.71	  0.00	 -0.71	  0.00]
[  0.00	  1.00	  0.00	  0.00]
[  0.71	  0.00	  0.71	  0.00]
[  0.00	  0.00	  0.00	  1.00]


##### Rotation um die z-Achse:

$$
   ^{Z}_{U}R_Y(\phi)  =    
   \left( \begin{array}{rrrr}       
      cos(\phi) &  sin(\phi) & 0 & 0 \\       
      -sin(\phi) & cos(\phi) & 0 & 0\\       
      0 & 0 & 1 & 0\\
      0 & 0 & 0 & 1\\
   \end{array}\right)
$$

In [12]:
T_U_Z_RotZ = np.array([[math.cos(phi),math.sin(phi),0,0],[-math.sin(phi),math.cos(phi),0,0],[0,0,1,0],[0,0,0,1]])

In [13]:
print("phi = ",end=""); print(phi,end="\n\n");
print("T_U_Z_RotZ(phi) = ",end="\n\n"); plot4x4Mat(T_U_Z_RotZ)

phi = 0.785398163375

T_U_Z_RotZ(phi) = 

[  0.71	  0.71	  0.00	  0.00]
[ -0.71	  0.71	  0.00	  0.00]
[  0.00	  0.00	  1.00	  0.00]
[  0.00	  0.00	  0.00	  1.00]


### (II.3) Berechung der Koordinaten von P für das Zielkoordinatensystem Z

#### Rotation um die X-Achse:

$$ ^{Z}P ~=~ ^{Z}_{U}T \cdot~ ^U{P}  ~=~      
   ^{Z}_{U}R_X(\phi)  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & 0 \\       
      0 & cos(\phi) & sin(\phi) &  0 \\       
      0 & -sin(\phi) & cos(\phi) & 0 \\           
      0 & 0 & 0 & 1\\
   \end{array}\right)
$$


 $$ ^{Z}P =  \left( \begin{array}{r} ^{Z}x \\ ^{Z}y \\ ^{Z}z \\ 1 \\ \end{array}\right)  $$

In [14]:
P_Z = T_U_Z_RotX @ P_U;

In [15]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_RotX = ");
plot4x4Mat(T_U_Z_RotX)
print("\n\nP_U = ",end="\n")
print(P_U,end="\n\n")
print("P_Z = ",end="\n"); print(P_Z)

T_U_Z_RotX = 
[  1.00	  0.00	  0.00	  0.00]
[  0.00	  0.71	  0.71	  0.00]
[  0.00	 -0.71	  0.71	  0.00]
[  0.00	  0.00	  0.00	  1.00]


P_U = 
[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]

P_Z = 
[[10.32      ]
 [29.86819044]
 [ 2.8567114 ]
 [ 1.        ]]


#### Rotation um die Y-Achse:

$$ ^{Z}P ~=~ ^{Z}_{U}T \cdot~ ^U{P}  ~=~    
   ^{Z}_{U}R_Y(\phi)  =    
   \left( \begin{array}{rrrr}       
       cos(\phi) & 0 & -sin(\phi) & 0  \\       
      0 & 1 & 0 & 0 \\       
      sin(\phi) & 0 &  cos(\phi) & 0\\           
      0 & 0 & 0 & 1 \\
   \end{array}\right)
   \cdot
   \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right)
$$

 $$ ^{Z}P =  \left( \begin{array}{r} ^{Z}x \\ ^{Z}y \\ ^{Z}z \\ 1 \\ \end{array}\right)  $$

In [16]:
P_Z = T_U_Z_RotY @ P_U;

In [17]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_RotY = ")
plot4x4Mat(T_U_Z_RotY)
print("\n\nP_U = ",end="\n")
print(P_U,end="\n\n")
print("P_Z = ",end="\n\n"); print(P_Z)

T_U_Z_RotY = 
[  0.71	  0.00	 -0.71	  0.00]
[  0.00	  1.00	  0.00	  0.00]
[  0.71	  0.00	  0.71	  0.00]
[  0.00	  0.00	  0.00	  1.00]


P_U = 
[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]

P_Z = 

[[-9.06510893]
 [19.1       ]
 [23.6597929 ]
 [ 1.        ]]


#### Rotation um die Z-Achse:

$$ ^{Z}P ~=~ ^{Z}_{U}T \cdot~ ^U{P}  ~=~      
   ^{Z}_{U}R_Y(\phi)  =    
   \left( \begin{array}{rrrr}       
      cos(\phi) &  sin(\phi) & 0 & 0 \\       
      -sin(\phi) & cos(\phi) & 0 & 0\\       
      0 & 0 & 1 & 0 \\
      0 & 0 & 0 & 1 \\
   \end{array}\right)
   \cdot
   \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right)
$$

$$ ^{Z}P =  \left( \begin{array}{r} ^{Z}x \\ ^{Z}y \\ ^{Z}z \\ 1 \\ \end{array}\right)  $$

In [18]:
P_Z = T_U_Z_RotZ @ P_U;

In [19]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_RotZ = ");
plot4x4Mat(T_U_Z_RotZ);
print("\n\nP_U = ",end="\n")
print(P_U,end="\n\n")
print("P_Z = ",end="\n"); print(P_Z)

T_U_Z_RotZ = 
[  0.71	  0.71	  0.00	  0.00]
[ -0.71	  0.71	  0.00	  0.00]
[  0.00	  0.00	  1.00	  0.00]
[  0.00	  0.00	  0.00	  1.00]


P_U = 
[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]

P_Z = 
[[20.8030815 ]
 [ 6.20839754]
 [23.14      ]
 [ 1.        ]]


### (II.4) Mehr als eine Rotation

Im Grunde lässt sich jede Rotationen als eine Kombination, d.h. Hintereinanderausführung) der drei oben definerten Rotationen (um die X-, Y- und Z-Achse) beschreiben.

$$ 
   ^{Z}_{U}R_X(\phi_x)  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & 0 \\       
      0 & cos(\phi) & sin(\phi) & 0  \\       
      0 & -sin(\phi) & cos(\phi) & 0\\           
      0 & 0 & 0 & 1\\
   \end{array}\right)
$$

$$
   ^{Z}_{U}R_Y(\phi_y)  =    
   \left( \begin{array}{rrrr}       
       cos(\phi) & 0 & -sin(\phi) & 0 \\       
      0 & 1 & 0 & 0 \\       
      sin(\phi) & 0 &  cos(\phi) & 0 \\
      0 & 0 & 0 & 1\\
   \end{array}\right)
$$   

$$
   ^{Z}_{U}R_Z(\phi_z)  =    
   \left( \begin{array}{rrrr}       
      cos(\phi) &  sin(\phi) & 0 & 0\\       
      -sin(\phi) & cos(\phi) & 0 & 0\\       
      0 & 0 & 1 & 1\\
      0 & 0 & 0 & 1\\
   \end{array}\right)
$$

Dabei können die Rotationen in beliebieger Reihenfolge ausgeführt werden. Wird z.B. erst die Rotation um die X-Achse (Rotationswinkel $phi_x$), dann um die Y-Achse ($phi_y$) und zuletzt um die Z-Achse ($phi_z$) ausgeführt, dann ergibt sich die HTM für diese Rotionen wie folgt:

$$ 
 ^{Z}_{U}R_{XYZ}(\phi_x,\phi_y,\phi_z) =  R_Z(\phi_z) \cdot R_Y(\phi_y) \cdot R_X(\phi_x) 
$$

Die Rotationen können jedoch in jeder beliebigen Reihenfolge ausgeführt werden. Im Allgemeinen sind dann die Ergebnisse, d.h. die HTMs, verschieden. Die Reihenfolge der Rotationen und die der Matrizenmultiplikationen ist immer zu beachten.

Es ist leicht zu sehen, dass es 6 verschiedene Möglichkeiten der Reihenfolge Hintereinanderausführung der Rotationen der 3 Achsen gibt. Die restlichen Kombinationsmglichkeiten sind wie folgt:

$$ 
 ^{Z}_{U}R_{XZY}(\phi_x,\phi_z,\phi_y) =  R_Y(\phi_y) \cdot R_Z(\phi_z) \cdot R_X(\phi_x) 
$$

$$ 
 ^{Z}_{U}R_{YXZ}(\phi_y,\phi_x,\phi_z) =  R_Z(\phi_z) \cdot R_X(\phi_x) \cdot R_Y(\phi_y) 
$$

$$ 
 ^{Z}_{U}R_{YZX}(\phi_y,\phi_z,\phi_x) =  R_X(\phi_x) \cdot R_Z(\phi_z) \cdot R_Y(\phi_y) 
$$

$$ 
 ^{Z}_{U}R_{ZXY}(\phi_z,\phi_x,\phi_y) =  R_Y(\phi_y) \cdot R_X(\phi_x) \cdot R_Z(\phi_z) 
$$

$$ 
 ^{Z}_{U}R_{ZYX}(\phi_z,\phi_y,\phi_x) =  R_X(\phi_x) \cdot R_Y(\phi_y) \cdot R_Z(\phi_z) 
$$

In [20]:
phi_x = PI/3
phi_y = 2*PI/5
phi_z = -PI/2

In [21]:
#Ausgabe der Berechnungsergebnisse
print("phi_x = ",end=""); print(phi_x)
print("phi_y = ",end=""); print(phi_y)
print("phi_z = ",end=""); print(phi_z)

phi_x = 1.0471975511666667
phi_y = 1.2566370614
phi_z = -1.57079632675


In [22]:
T_U_Z_RotX = np.array([[1,0,0,0],[0,math.cos(phi_x),math.sin(phi_x),0],[0,-math.sin(phi_x),math.cos(phi_x),0],[0,0,0,1]])

In [23]:
T_U_Z_RotY = np.array([[math.cos(phi_y),0,-math.sin(phi_y),0],[0,1,0,0],[math.sin(phi_y),0,math.cos(phi_y),0],[0,0,0,1]])

In [24]:
T_U_Z_RotZ = np.array([[math.cos(phi_z),math.sin(phi_z),0,0],[-math.sin(phi_z),math.cos(phi_z),0,0],[0,0,1,0],[0,0,0,1]])

In [25]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_RotX = ",end="\n"); plot4x4Mat(T_U_Z_RotX) 
print("\n\nT_U_Z_RotY = ",end="\n"); plot4x4Mat(T_U_Z_RotY)
print("\n\nT_U_Z_RotZ = ",end="\n"); plot4x4Mat(T_U_Z_RotZ)

T_U_Z_RotX = 
[  1.00	  0.00	  0.00	  0.00]
[  0.00	  0.50	  0.87	  0.00]
[  0.00	 -0.87	  0.50	  0.00]
[  0.00	  0.00	  0.00	  1.00]


T_U_Z_RotY = 
[  0.31	  0.00	 -0.95	  0.00]
[  0.00	  1.00	  0.00	  0.00]
[  0.95	  0.00	  0.31	  0.00]
[  0.00	  0.00	  0.00	  1.00]


T_U_Z_RotZ = 
[  0.00	 -1.00	  0.00	  0.00]
[  1.00	  0.00	  0.00	  0.00]
[  0.00	  0.00	  1.00	  0.00]
[  0.00	  0.00	  0.00	  1.00]


$$ 
 ^{Z}_{U}R_{ZYX}(\phi_z,\phi_y,\phi_x) =  R_X(\phi_x) \cdot R_Y(\phi_y) \cdot R_Z(\phi_z) 
$$

In [26]:
T_U_Z_RotZYX = T_U_Z_RotX @ T_U_Z_RotY @ T_U_Z_RotZ

In [27]:
print("T_U_Z_RotZYX = ",end="\n"); plot4x4Mat(T_U_Z_RotZYX)

T_U_Z_RotZYX = 
[  0.00	 -0.31	 -0.95	  0.00]
[  0.50	 -0.82	  0.27	  0.00]
[ -0.87	 -0.48	  0.15	  0.00]
[  0.00	  0.00	  0.00	  1.00]


$$
 ^{Z}_{U}R_{ZXY}(\phi_z,\phi_x,\phi_y) =  R_Y(\phi_y) \cdot R_X(\phi_x) \cdot R_Z(\phi_z) 
$$

In [28]:
T_U_Z_RotZXY = T_U_Z_RotY @ T_U_Z_RotX @ T_U_Z_RotZ

In [29]:
print("T_U_Z_RotZXY = ",end="\n"); plot4x4Mat(T_U_Z_RotZXY)

T_U_Z_RotZXY = 
[  0.82	 -0.31	 -0.48	  0.00]
[  0.50	  0.00	  0.87	  0.00]
[ -0.27	 -0.95	  0.15	  0.00]
[  0.00	  0.00	  0.00	  1.00]


$$
 ^{Z}_{U}R_{YZX}(\phi_y,\phi_z,\phi_x) =  R_X(\phi_x) \cdot R_Z(\phi_z) \cdot R_Y(\phi_y) 
$$

In [30]:
T_U_Z_RotYZX = T_U_Z_RotX @ T_U_Z_RotZ @ T_U_Z_RotY

In [31]:
print("T_U_Z_RotYZX = ",end="\n"); plot4x4Mat(T_U_Z_RotYZX)

T_U_Z_RotYZX = 
[  0.00	 -1.00	 -0.00	  0.00]
[  0.98	  0.00	 -0.21	  0.00]
[  0.21	 -0.00	  0.98	  0.00]
[  0.00	  0.00	  0.00	  1.00]


$$ 
 ^{Z}_{U}R_{YXZ}(\phi_y,\phi_x,\phi_z) =  R_Z(\phi_z) \cdot R_X(\phi_x) \cdot R_Y(\phi_y) 
$$

In [32]:
T_U_Z_RotYXZ = T_U_Z_RotZ @ T_U_Z_RotX @ T_U_Z_RotY

In [33]:
print("T_U_Z_RotYXZ = ",end="\n"); plot4x4Mat(T_U_Z_RotYXZ)

T_U_Z_RotYXZ = 
[ -0.82	 -0.50	 -0.27	  0.00]
[  0.31	  0.00	 -0.95	  0.00]
[  0.48	 -0.87	  0.15	  0.00]
[  0.00	  0.00	  0.00	  1.00]


$$
 ^{Z}_{U}R_{XZY}(\phi_x,\phi_z,\phi_y) =  R_Y(\phi_y) \cdot R_Z(\phi_z) \cdot R_X(\phi_x) 
$$    

In [34]:
T_U_Z_RotXZY = T_U_Z_RotY @ T_U_Z_RotZ @ T_U_Z_RotX

In [35]:
print("T_U_Z_RotXZY = ",end="\n"); plot4x4Mat(T_U_Z_RotXZY)

T_U_Z_RotXZY = 
[  0.00	  0.67	 -0.74	  0.00]
[  1.00	  0.00	  0.00	  0.00]
[  0.00	 -0.74	 -0.67	  0.00]
[  0.00	  0.00	  0.00	  1.00]


$$
 ^{Z}_{U}R_{XYZ}(\phi_z,\phi_y,\phi_x) =  R_Z(\phi_z) \cdot R_Y(\phi_y) \cdot R_X(\phi_x) 
$$    

In [36]:
T_U_Z_RotXYZ = T_U_Z_RotZ @ T_U_Z_RotY @ T_U_Z_RotX

In [37]:
print("T_U_Z_RotXYZ = ",end="\n"); plot4x4Mat(T_U_Z_RotXYZ)

T_U_Z_RotXYZ = 
[  0.00	 -0.50	 -0.87	  0.00]
[  0.31	  0.82	 -0.48	  0.00]
[  0.95	 -0.27	  0.15	  0.00]
[  0.00	  0.00	  0.00	  1.00]


### (III) Übung

Berechnen Sie die Koordinaten des $^{Z}P$, also die Koordinaten des Punktes $P$ bzgl. des Koordinatensystems $Z$. Gegeben sind die Koordinaten des Punktes bzgl. Koordinatensystem $U$, also $^{U}P$.

#### (III.1) Vektor $^{U}P$ definieren

In [38]:
x_U = randint(-99,99)
y_U = randint(-99,99)
z_U = randint(-99,99)
P_U = np.array([[x_U],[y_U],[z_U],[1]])

In [39]:
#Ausgabe der Berechnungsergebnisse
print("P_U =",end="\n\n"); print(P_U)

P_U =

[[ 30]
 [ 25]
 [-93]
 [  1]]


#### (III.2) HTM $^{Z}_{U}T$ definieren

Für die Rotation um die $Z$ Achse mit Winkel $\phi$ soll die Rotationsmatrix berechnet werden. Tragen Sie dazu in der nächsten Zelle die korrekten Werte für die Matrix T_U_Z ein. (Hinweis: benutzen Sie die Python-Funktion math.sin(...) und math.cos(...), um die Werte in die Matrix einzutragen.)

In [40]:
phi = randint(-3,3)*(PI/2)
T_U_Z = np.array([[math.cos(phi),math.sin(phi),0,0],[-math.sin(phi),math.cos(phi),0,0],[0,0,1,0],[0,0,0,1]])

In [41]:
#Ausgabe der Ergebnisse
print("phi = ", end=""); print(phi);
print("T_U_Z = "); plot4x4Mat(T_U_Z);

phi = 4.71238898025
T_U_Z = 
[ -0.00	 -1.00	  0.00	  0.00]
[  1.00	 -0.00	  0.00	  0.00]
[  0.00	  0.00	  1.00	  0.00]
[  0.00	  0.00	  0.00	  1.00]


#### (III.3) Den Vektor $^{Z}P$ berechnen

In [42]:
P_Z = T_U_Z @ P_U

In [43]:
#Ausgabe der Ergebnisse
print("P_Z = "); print(P_Z);

P_Z = 
[[-25.]
 [ 30.]
 [-93.]
 [  1.]]
