# Koordinatentransformation für die Robotik

## (2) Homogene Transformationmatrix (HTM) für die Translation

Folgende Bibliotheken und Konstanten werden genutzt:

In [1]:
from matplotlib import pyplot as plt
import numpy as np
import math

PI = 3.14159

### (I) Punkt im Ursprungskoordinatensystem U definieren

$$ ^{U}P = \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right) $$

In [2]:
x_U = 10.32
y_U = 19.10
z_U = 23.14
print("x_U = ",end=""); print(x_U)
print("y_U = ",end=""); print(y_U)
print("z_U = ",end=""); print(z_U)

x_U = 10.32
y_U = 19.1
z_U = 23.14


In [3]:
P_U = np.array([[x_U],[y_U],[z_U],[1]])
print("P_U = ",end="\n\n"); print(P_U)

P_U = 

[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]


### (II) Definition der HTM

#### (II.1) HTM: Matrixgrundstruktur (ohne Translation u. Rotation)

$$ ^{Z}_{U}T  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & 0 \\       
      0 & 1 & 0 & 0 \\       
      0 & 0 & 1 & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
$$

In [4]:
T_U_Z = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print("T_U_Z = ",end="\n\n"); print(T_U_Z)

T_U_Z = 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### (II.2) HTM: Definition des Rotationsanteils

#### Rotationsmatrizen (für die Koordinatentransformation)

Rotationswinkel $\phi$ mit $\phi \in [0,2\pi)$.

Rotationsmatrizen für die Koordinatenachsen $X$, $Y$ und $Z$:
$$ 
   ^{Z}_{U}R(\phi)_X  =    
   \left( \begin{array}{rrr}       
      1 & 0 & 0 \\       
      0 & cos(\phi) & sin(\phi) \\       
      0 & -sin(\phi) & cos(\phi) \\           
   \end{array}\right)
$$

$$
   ^{Z}_{U}R(\phi)_Y  =    
   \left( \begin{array}{rrr}       
       cos(\phi) & 0 & -sin(\phi) \\       
      0 & 1 & 0 \\       
      sin(\phi) & 0 &  cos(\phi) \\           
   \end{array}\right)
$$   

$$
   ^{Z}_{U}R(\phi)_Y  =    
   \left( \begin{array}{rrr}       
      cos(\phi) &  sin(\phi) & 0 \\       
      -sin(\phi) & cos(\phi) & 0 \\       
      0 & 0 & 1 \\           
   \end{array}\right)
$$

Der Rotationswinkel $\phi$ hat den Drehsinn vom Ursprung zum Zielkoordinatensystem und ist im folgenden in der Einheit Radiant (rad) angegeben.

In [5]:
phi = PI/4;
print("phi = ", end=""); print(phi)

phi = 0.7853975


#### HTM mit Rotation

Wir betrachten wieder die einzelnen Rotationen, um die Achsen X, Y, Z.

##### Rotation um die X-Achse:

$$ 
   ^{Z}_{U}R(\phi)_X  =    
   \left( \begin{array}{rrr}       
      1 & 0 & 0 \\       
      0 & cos(\phi) & sin(\phi) \\       
      0 & -sin(\phi) & cos(\phi) \\           
   \end{array}\right)
$$

In [6]:
T_U_Z_RotX = np.array([[1,0,0,0],[0,math.cos(phi),math.sin(phi),0],[0,-math.sin(phi),math.cos(phi),0],[0,0,0,1]])

In [7]:
print("phi = ",end=""); print(phi,end="\n\n");
print("T_U_Z_RotX(phi) = ",end="\n\n"); print(T_U_Z_RotX)

phi = 0.7853975

T_U_Z_RotX(phi) = 

[[ 1.          0.          0.          0.        ]
 [ 0.          0.70710725  0.70710631  0.        ]
 [ 0.         -0.70710631  0.70710725  0.        ]
 [ 0.          0.          0.          1.        ]]


##### Rotation um die y-Achse:

$$
   ^{Z}_{U}R(\phi)_Y  =    
   \left( \begin{array}{rrr}       
       cos(\phi) & 0 & -sin(\phi) \\       
      0 & 1 & 0 \\       
      sin(\phi) & 0 &  cos(\phi) \\           
   \end{array}\right)
$$ 

In [8]:
T_U_Z_RotY = np.array([[math.cos(phi),0,-math.sin(phi),0],[0,1,0,0],[math.sin(phi),0,math.cos(phi),0],[0,0,0,1]])

In [9]:
print("phi = ",end=""); print(phi,end="\n\n");
print("T_U_Z_RotY(phi) = ",end="\n\n"); print(T_U_Z_RotY)

phi = 0.7853975

T_U_Z_RotY(phi) = 

[[ 0.70710725  0.         -0.70710631  0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.70710631  0.          0.70710725  0.        ]
 [ 0.          0.          0.          1.        ]]


##### Rotation um die z-Achse:

$$
   ^{Z}_{U}R(\phi)_Y  =    
   \left( \begin{array}{rrr}       
      cos(\phi) &  sin(\phi) & 0 \\       
      -sin(\phi) & cos(\phi) & 0 \\       
      0 & 0 & 1 \\           
   \end{array}\right)
$$

In [10]:
T_U_Z_RotZ = np.array([[math.cos(phi),math.sin(phi),0,0],[-math.sin(phi),math.cos(phi),0,0],[0,0,1,0],[0,0,0,1]])

In [11]:
print("phi = ",end=""); print(phi,end="\n\n");
print("T_U_Z_RotZ(phi) = ",end="\n\n"); print(T_U_Z_RotZ)

phi = 0.7853975

T_U_Z_RotZ(phi) = 

[[ 0.70710725  0.70710631  0.          0.        ]
 [-0.70710631  0.70710725  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


### (II.3) Berechung der Koordinaten von P für das Zielkoordinatensystem Z

#### Rotation um die X-Achse:

$$ ^{Z}P ~=~ ^{Z}_{U}T \cdot~ ^U{P}  ~=~      
   ^{Z}_{U}R(\phi)_X  =    
   \left( \begin{array}{rrr}       
      1 & 0 & 0 \\       
      0 & cos(\phi) & sin(\phi) \\       
      0 & -sin(\phi) & cos(\phi) \\           
   \end{array}\right)
$$


 $$ ^{Z}P =  \left( \begin{array}{r} x_Z \\ x_Z \\ x_Z \\ \end{array}\right)  $$

In [12]:
P_Z = T_U_Z_RotX @ P_U;

In [13]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_RotX = ");
print(T_U_Z_RotX,end="\n\n")
print("P_U = ",end="\n")
print(P_U,end="\n\n")
print("P_Z = ",end="\n\n"); print(P_Z)

T_U_Z_RotX = 
[[ 1.          0.          0.          0.        ]
 [ 0.          0.70710725  0.70710631  0.        ]
 [ 0.         -0.70710631  0.70710725  0.        ]
 [ 0.          0.          0.          1.        ]]

P_U = 
[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]

P_Z = 

[[10.32      ]
 [29.86818854]
 [ 2.85673121]
 [ 1.        ]]


#### Rotation um die Y-Achse:

$$ ^{Z}P ~=~ ^{Z}_{U}T \cdot~ ^U{P}  ~=~    
   ^{Z}_{U}R(\phi)_Y  =    
   \left( \begin{array}{rrr}       
       cos(\phi) & 0 & -sin(\phi) \\       
      0 & 1 & 0 \\       
      sin(\phi) & 0 &  cos(\phi) \\           
   \end{array}\right)
   \cdot
   \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right)
$$

 $$ ^{Z}P =  \left( \begin{array}{r} x_Z \\ x_Z \\ x_Z \\ \end{array}\right)  $$

In [14]:
P_Z = T_U_Z_RotY @ P_U;

In [15]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_RotY = ");
print(T_U_Z_RotY,end="\n\n")
print("P_U = ",end="\n")
print(P_U,end="\n\n")
print("P_Z = ",end="\n\n"); print(P_Z)

T_U_Z_RotY = 
[[ 0.70710725  0.         -0.70710631  0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.70710631  0.          0.70710725  0.        ]
 [ 0.          0.          0.          1.        ]]

P_U = 
[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]

P_Z = 

[[-9.06509324]
 [19.1       ]
 [23.65979891]
 [ 1.        ]]


#### Rotation um die Z-Achse:

$$ ^{Z}P ~=~ ^{Z}_{U}T \cdot~ ^U{P}  ~=~    
   ^{Z}_{U}R(\phi)_Y  =    
   ^{Z}_{U}R(\phi)_Y  =    
   \left( \begin{array}{rrr}       
      cos(\phi) &  sin(\phi) & 0 \\       
      -sin(\phi) & cos(\phi) & 0 \\       
      0 & 0 & 1 \\           
   \end{array}\right)
   \cdot
   \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right)
$$

 $$ ^{Z}P =  \left( \begin{array}{r} x_Z \\ x_Z \\ x_Z \\ \end{array}\right)  $$

In [16]:
P_Z = T_U_Z_RotZ @ P_U;

In [17]:
#Ausgabe der Berechnungsergebnisse
print("T_U_Z_RotZ = ");
print(T_U_Z_RotZ,end="\n\n")
print("P_U = ",end="\n")
print(P_U,end="\n\n")
print("P_Z = ",end="\n\n"); print(P_Z)

T_U_Z_RotZ = 
[[ 0.70710725  0.70710631  0.          0.        ]
 [-0.70710631  0.70710725  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]

P_U = 
[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]

P_Z = 

[[20.80307738]
 [ 6.20841134]
 [23.14      ]
 [ 1.        ]]
