# Koordinatentransformation für die Robotik

## (1) Homogene Transformationmatrix (HTM) für die Translation

Folgende Bibliotheken und Konstanten werden genutzt:

In [1]:
from matplotlib import pyplot as plt
from random import *
import numpy as np
import math

def plot4x4Mat(m):
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[0,0],m[0,1],m[0,2],m[0,3]))
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[1,0],m[1,1],m[1,2],m[1,3]))
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[2,0],m[2,1],m[2,2],m[2,3]))
    print("[%6.2f\t%6.2f\t%6.2f\t%6.2f]"%(m[3,0],m[3,1],m[3,2],m[3,3]))

#### (I) Punkt im Ursprungskoordinatensystem U definieren

$$ ^{U}P = \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right) $$

In [2]:
x_U = 10.32
y_U = 19.10
z_U = 23.14

In [3]:
#Ausgabe der Berechnungsergebnisse
print("x_U = ",end=""); print(x_U)
print("y_U = ",end=""); print(y_U)
print("z_U = ",end=""); print(z_U)

x_U = 10.32
y_U = 19.1
z_U = 23.14


In [4]:
P_U = np.array([[x_U],[y_U],[z_U],[1]])

In [5]:
#Ausgabe der Berechnungsergebnisse
print("P_U = ",end="\n\n"); print(P_U)

P_U = 

[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]


#### (II) Definition der HTM

#### (II.1) HTM: Matrixgrundstruktur (ohne Translation u. Rotation)

$$ ^{Z}_{U}T  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & 0 \\       
      0 & 1 & 0 & 0 \\       
      0 & 0 & 1 & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
$$

In [6]:
T_U_Z = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

In [7]:
#Ausgabe der Berechnungsergebnisse
print("T_U_U = ",end="\n\n"); print(T_U_Z)

T_U_U = 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#### (II.2) HTM: Definition des Translationsanteils

##### Translationsvektor

 $$ ^{Z}V =  \left( \begin{array}{r} x \\ y \\ z \\ \end{array}\right)  $$

Der Translationsvektor ist bzgl. des Zielkoordinatensystems Z gegeben. Dieser Translationsvektor ist daher mit $ ^{Z} V$ bezeichnet.

In [8]:
x = 1.3
y = -3.9
z = 2.9

In [9]:
#Ausgabe der Berechnungsergebnisse
print("x = ",end=""); print(x)
print("y = ",end=""); print(y)
print("z = ",end=""); print(z)

x = 1.3
y = -3.9
z = 2.9


##### HTM mit Translation

Der Translationsvektor $^{Z}V$ wird einfach in die 4.Spalte der HTM $~ ^{Z}_{U}T~$ "eingefügt".

$$ ^{Z}_{U}T  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & x \\       
      0 & 1 & 0 & y \\       
      0 & 0 & 1 & z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
$$

In [10]:
T_U_Z = np.array([[1,0,0,x],[0,1,0,y],[0,0,1,z],[0,0,0,1]])

In [11]:

print("T_U_Z = ",end="\n\n"); print(T_U_Z)

T_U_Z = 

[[ 1.   0.   0.   1.3]
 [ 0.   1.   0.  -3.9]
 [ 0.   0.   1.   2.9]
 [ 0.   0.   0.   1. ]]


#### (II.3) Berechung der Koordinaten von P für das Zielkoordinatensystem Z

$$ ^{Z}P ~=~ ^{Z}_{U}T \cdot~ ^U{P}  ~=~    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & x \\       
      0 & 1 & 0 & y \\       
      0 & 0 & 1 & z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
   \cdot
   \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right)
$$


 $$ ^{Z}P =  \left( \begin{array}{r} x_Z \\ x_Z \\ x_Z \\ \end{array}\right)  $$

In [12]:
P_Z = T_U_Z @ P_U

In [13]:
#Ausgabe der Berechnungsergebnisse
print("P_Z =",end="\n\n"); print(P_Z)

P_Z =

[[11.62]
 [15.2 ]
 [26.04]
 [ 1.  ]]


Daraus ergeben sich die Koordinaten ($^{Z}x$,$^{Z}y$,$^{Z}z$) des Punktes $^{Z}P$ im Zielkoordinatensystem $Z$: 

In [14]:
x_Z = P_Z[0,0]
y_Z = P_Z[1,0]
z_Z = P_Z[2,0]

In [15]:
#Ausgabe der Berechnungsergebnisse
print("x_Z = ",end=""); print(x_Z)
print("y_Z = ",end=""); print(y_Z)
print("z_Z = ",end=""); print(z_Z)

x_Z = 11.620000000000001
y_Z = 15.200000000000001
z_Z = 26.04


### (III) Übung

Berechnen Sie die Koordinaten des $^{Z}P$, also die Koordinaten des Punktes $P$ bzgl. des Koordinatensystems $Z$. Gegeben sind die Koordinaten des Punktes bzgl. Koordinatensystem $U$, also $^{U}P$.

#### (III.1) Vektor $^{U}P$ definieren

In [16]:
x_U = randint(-99,99)
y_U = randint(-99,99)
z_U = randint(-99,99)
P_U = np.array([[x_U],[y_U],[z_U],[1]])

In [17]:
#Ausgabe der Berechnungsergebnisse
print("P_U =",end="\n\n"); print(P_U)

P_U =

[[-81]
 [ 44]
 [ 40]
 [  1]]


#### (III.2) HTM $^{Z}_{U}T$ definieren

Der Translationsvektor in homogenen Koordinaten $^{Z}V$ ist:

In [18]:
V_Z = np.array([[randint(-99, 99)],[randint(-100, 100)],[randint(-100, 100)],[1]])

In [19]:
#Ausgabe der Berechnungsergebnisse
print("V_Z =",end="\n\n"); print(V_Z)

V_Z =

[[-92]
 [ 85]
 [-21]
 [  1]]


Definieren Sie die HTM $^{Z}_{U}T$ wie oben angeben.
$$ ^{Z}_{U}T  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & ^{Z}V_x \\       
      0 & 1 & 0 & ^{Z}V_y \\       
      0 & 0 & 1 & ^{Z}V_z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
$$
Tragen Sie dazu in der nächsten Zelle die korrekten Werte für die Matrix T_U_Z ein.

In [20]:
T_U_Z = np.array([[1,0,0,V_Z[0,0]],[0,1,0,V_Z[1,0]],[0,0,1,V_Z[2,0]],[0,0,0,1]])

In [21]:
#Ausgabe der Ergebnisse
print("T_U_Z = ");
plot4x4Mat(T_U_Z)

T_U_Z = 
[  1.00	  0.00	  0.00	-92.00]
[  0.00	  1.00	  0.00	 85.00]
[  0.00	  0.00	  1.00	-21.00]
[  0.00	  0.00	  0.00	  1.00]


#### (III.3) Den Vektor $^{Z}P$ berechnen

In [22]:
P_Z = T_U_Z @ P_U

In [23]:
#Ausgabe der Ergebnisse
print("P_Z = "); print(P_Z);

P_Z = 
[[-173]
 [ 129]
 [  19]
 [   1]]
