# Koordinatentransformation für die Robotik

## Homogene Transformationmatrix (HTM) für die Translation

Folgende Bibliotheken werden genutzt:

In [1]:
from matplotlib import pyplot as plt
import numpy as np
import math

#### (I) Punkt im Ursprungskoordinatensystem U definieren

$$ ^{U}P = \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right) $$

In [2]:
x_U = 10.32
y_U = 19.10
z_U = 23.14
print("x_U = ",end=""); print(x_U)
print("y_U = ",end=""); print(y_U)
print("z_U = ",end=""); print(z_U)

x_U = 10.32
y_U = 19.1
z_U = 23.14


In [3]:
P_U = np.array([[x_U],[y_U],[z_U],[1]])
print("P_U = ",end="\n\n"); print(P_U)

P_U = 

[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]


#### (II) Definition der HTM

#### (II.1) HTM: Matrixgrundstruktur (ohne Translation u. Rotation)

$$ ^{Z}_{U}T  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & 0 \\       
      0 & 1 & 0 & 0 \\       
      0 & 0 & 1 & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
$$

In [4]:
T_U_Z = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print("T_U_U = ",end="\n\n"); print(T_U_Z)

T_U_U = 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#### (II.2) HTM: Definition des Translationsanteils

##### Translationsvektor

 $$ ^{Z}V =  \left( \begin{array}{r} x \\ y \\ z \\ \end{array}\right)  $$

Der Translationsvektor ist bzgl. des Zielkoordinatensystems Z gegeben. Dieser Translationsvektor ist daher mit $ ^{Z} V$ bezeichnet.

In [5]:
x = 1.3
y = -3.9
z = 2.9
print("x = ",end=""); print(x)
print("y = ",end=""); print(y)
print("z = ",end=""); print(z)

x = 1.3
y = -3.9
z = 2.9


##### HTM mit Translation

Der Translationsvektor $^{Z}V$ wird einfach in die 4.Spalte der HTM $~ ^{Z}_{U}T~$ "eingefügt".

$$ ^{Z}_{U}T  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & x \\       
      0 & 1 & 0 & y \\       
      0 & 0 & 1 & z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
$$

In [6]:
T_U_Z = np.array([[1,0,0,x],[0,1,0,y],[0,0,1,z],[0,0,0,1]])
print("T_U_Z = ",end="\n\n"); print(T_U_Z)

T_U_Z = 

[[ 1.   0.   0.   1.3]
 [ 0.   1.   0.  -3.9]
 [ 0.   0.   1.   2.9]
 [ 0.   0.   0.   1. ]]


#### (II.3) Berechung der Koordinaten von P für das Zielkoordinatensystem Z

$$ ^{Z}P ~=~ ^{Z}_{U}T \cdot~ ^U{P}  ~=~    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & x \\       
      0 & 1 & 0 & y \\       
      0 & 0 & 1 & z \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
   \cdot
   \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right)
$$


 $$ ^{Z}P =  \left( \begin{array}{r} x_Z \\ x_Z \\ x_Z \\ \end{array}\right)  $$

In [7]:
P_Z = T_U_Z @ P_U
print("P_Z =",end="\n\n"); print(P_Z)

P_Z =

[[11.62]
 [15.2 ]
 [26.04]
 [ 1.  ]]


Daraus ergeben sich die Koordinaten ($^{Z}x$,$^{Z}y$,$^{Z}z$) des Punktes $^{Z}P$ im Zielkoordinatensystem $Z$: 

In [8]:
x_Z = P_Z[0,0]
y_Z = P_Z[1,0]
z_Z = P_Z[2,0]
print("x_Z = ",end=""); print(x_Z)
print("y_Z = ",end=""); print(y_Z)
print("z_Z = ",end=""); print(z_Z)

x_Z = 11.620000000000001
y_Z = 15.200000000000001
z_Z = 26.04
