# Koordinatentransformation für die Robotik

## Homogene Transformationmatrix (HTM) für die Translation

Folgende Bibliotheken werden genutzt:

In [10]:
from matplotlib import pyplot as plt
import numpy as np
import math

#### (I) Punkt im Ursprungskoordinatensystem U definieren

$$ ^{U}P = \left( \begin{array}{r} ^{U}x \\ ^{U}y \\ ^{U}z \\ 1 \end{array}\right) $$

In [11]:
x_U = 10.32
y_U = 19.10
z_U = 23.14
print("x_U = ",end=""); print(x_U)
print("y_U = ",end=""); print(y_U)
print("z_U = ",end=""); print(z_U)

x_U = 10.32
y_U = 19.1
z_U = 23.14


In [12]:
P_U = np.array([[x_U],[y_U],[z_U],[1]])
print("P_U = ",end="\n\n"); print(P_U)

P_U = 

[[10.32]
 [19.1 ]
 [23.14]
 [ 1.  ]]


#### (II) Definition der HTM

#### (II.1) HTM: Matrixgrundstruktur (ohne Translation u. Rotation)

$$ ^{Z}_{U}T  =    
   \left( \begin{array}{rrrr}       
      1 & 0 & 0 & 0 \\       
      0 & 1 & 0 & 0 \\       
      0 & 0 & 1 & 0 \\       
      0 & 0 & 0 & 1 \\    
   \end{array}\right)
$$

In [13]:
T_U_Z = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print("T_U_U = ",end="\n\n"); print(T_U_Z)

T_U_U = 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#### (II.2) HTM: Definition des Rotationsanteils

##### Rotationsmatrix (für die Koordinatentransformation)

Rotationswinkel $\phi$ mit $\phi \in (0,2\pi)$.

Rotationsmatrizen für die Koordinatenachsen $X$, $Y$ und $Z$:
$$ 
   ^{Z}_{U}R(\phi)_X  =    
   \left( \begin{array}{rrr}       
      0 & 0 & 0 \\       
      0 & 0 & 0 \\       
      0 & 0 & 0 \\           
   \end{array}\right)
~~~~~~   
   ^{Z}_{U}R(\phi)_Y  =    
   \left( \begin{array}{rrr}       
      0 & 0 & 0 \\       
      0 & 0 & 0 \\       
      0 & 0 & 0 \\           
   \end{array}\right)
~~~~~~   
   ^{Z}_{U}R(\phi)_Y  =    
   \left( \begin{array}{rrr}       
      0 & 0 & 0 \\       
      0 & 0 & 0 \\       
      0 & 0 & 0 \\           
   \end{array}\right)
$$